### PR TITLE
Using ethtool to disable lldp for i40e nics

### PR DESCRIPTION
**Pull request by xtrusia**
Resolves: #9

### CODE REVIEW

**Comment by xtrusia** [comment]
I'm trying to test this but prior to that, I would like to get any advice. Thanks in advance.

**Comment by MrClayPole** [comment]
I'm not sure this patch will fully address the issue as it's still getting the "nic name" via debugfs, which is unavailable when secureboot is enabled. A college has created the following patch which addresses this issue. Let me know what you think
https://github.com/MrClayPole/charm-lldpd/commit/aaa0a075b5faa6f9a3562c7a1b9aabcdb421e014

**Comment by xtrusia** [comment]
> I'm not sure this patch will fully address the issue as it's still getting the "nic name" via debugfs, which is unavailable when secureboot is enabled. A college has created the following patch which addresses this issue. Let me know what you think [MrClayPole@aaa0a07](https://github.com/MrClayPole/charm-lldpd/commit/aaa0a075b5faa6f9a3562c7a1b9aabcdb421e014)

I think it is good. just curious that reading path = "/sys/kernel/debug/i40e" is also blocked? I thought err log said only when it writes value. permission denied. a bit wonder if handling string with grep is enough here.

**Comment by janvs0** [comment]
Hi! Thanks for looking at this.

You can read the path, but it contains BDF addresses which you can't pass to ethtool (as nic). I think we're going to need the device name for devices that have the i40e driver attached, hence the "interesting" grep from kern.log.

**Comment by xtrusia** [comment]
> Hi! Thanks for looking at this.
> 
> You can read the path, but it contains BDF addresses which you can't pass to ethtool (as nic). I think we're going to need the device name for devices that have the i40e driver attached, hence the "interesting" grep from kern.log.

Thanks a lot. I'm looking forward to your PR instead of mine :)

**Comment by MrClayPole** [comment]
We've submitted our pull request. Let us know what you think

**Pull request closed without merging**
